# AdaBoostClassifier模型配置文件
# 全局配置
[global]
    model = "adaboost"
    device = "auto"  # 自动检测GPU/CPU
    seed = 42
    outdir = "experiment/tumor_imm/ccRCC_imm"

# 数据集配置
[dataset]
    test_size = 0.2
    val_size = 0.2
    random_state = 42

# AdaBoostClassifier模型配置
[adaboost]
    # 基础参数
    n_estimators = [50, 100, 200]  # 弱学习器数量
    learning_rate = [0.01, 0.1, 0.5, 1.0]  # 学习率
    algorithm = ["SAMME", "SAMME.R"]  # 算法类型
    
    # 其他可选参数
    random_state = 42  # 随机种子
    
    # 交叉验证配置
    cv_folds = 5  # 交叉验证折数
    cv_scoring = "roc_auc"  # 评估指标
    n_jobs = 8  # 并行作业数，-1表示使用所有CPU核心
    
    # 特征选择配置
    feature_selection = true
    selection_method = "lasso"
    n_features = 100
    selection_alpha = 0.01
    
    # 数据预处理配置
    [adaboost.preprocessing]
        fill_na = true
        fill_method = "mean"
        scale_data = true
        scale_method = "standard"

# 训练配置
[training]
    verbose = 1
    save_model = true
    save_format = "pickle"
    save_data = true

# 评估配置
[evaluation]
    metrics = ["roc_auc", "classification_report"]
    save_predictions = true
    save_probabilities = true 