seed = 888888888
dataset = 'lym_sex'
mode = "one mode" # one mode
piror_knowledge = "data/c1.all.v2025.1.Hs.symbols.gmt"
device = "cuda"
freeze_prior = true

[deep_mode]
    num_layers = 10
    num_sub_sets = 2

[params]
    model = 'nnea'
    batch_size = 32
    num_sets = 20
    set_min_size = 10
    set_max_size = 50
    alpha = 0.25
    hidden_dim=128
    attn_hidden_dim=64
    learning_rate = 0.001
    num_epochs = 10000
    classifier = 'linear' # linear or attention
#    model_pt = 'checkpoints/2025_06_17_lym_sex_attention/model_nnea_batch_size_32_num_sets_20_set_min_size_10_set_max_size_50_alpha_0.25_hidden_dim_128_attn_hidden_dim_64_learning_rate_0.001_num_epochs_10000_classifier_attention_checkpoint.pt'
