# MLPClassifier模型配置文件
# 全局配置
[global]
    model = "mlp"
    device = "auto"  # 自动检测GPU/CPU
    seed = 42
    outdir = "experiment/tumor_imm/ccRCC_imm"

# 数据集配置
[dataset]
    test_size = 0.2
    val_size = 0.2
    random_state = 42

# MLPClassifier模型配置
[mlp]
    # 基础参数
    hidden_layer_sizes = [[50], [100], [50, 50], [100, 50]]  # 隐藏层大小
    activation = ["relu", "tanh"]  # 激活函数
    alpha = [0.0001, 0.001, 0.01]  # L2正则化参数
    learning_rate = ["constant", "adaptive"]  # 学习率调度
    max_iter = [1000]  # 最大迭代次数
    
    # 其他可选参数
    random_state = 42  # 随机种子
    early_stopping = false  # 早停
    validation_fraction = 0.1  # 验证集比例
    n_iter_no_change = 10  # 无改善迭代数
    tol = 1e-4  # 收敛容差
    
    # 交叉验证配置
    cv_folds = 5  # 交叉验证折数
    cv_scoring = "roc_auc"  # 评估指标
    n_jobs = 8  # 并行作业数，-1表示使用所有CPU核心
    
    # 特征选择配置
    feature_selection = true
    selection_method = "lasso"
    n_features = 100
    selection_alpha = 0.01
    
    # 数据预处理配置
    [mlp.preprocessing]
        fill_na = true
        fill_method = "mean"
        scale_data = true
        scale_method = "standard"

# 训练配置
[training]
    verbose = 1
    save_model = true
    save_format = "pickle"
    save_data = true

# 评估配置
[evaluation]
    metrics = ["roc_auc", "classification_report"]
    save_predictions = true
    save_probabilities = true 