# nnea模型配置文件
# 全局配置
[global]
    model = "nnea_umap"
    device = "auto"  # 自动检测GPU/CPU
    seed = 42
    outdir = "experiment/melanoma_imm_nnea"
    task = "umap"

# 数据集配置
[dataset]
    test_size = 0.2
    val_size = 0.2
    random_state = 42
    feature_selection = true
    selection_method = "differential_expression"
    n_features = 7000

# nnea模型配置
[nnea]
    [nnea.piror_knowledge]
        use_piror_knowledge = false
        piror_path = "data/genesets/c2.cp.kegg_legacy.v2025.1.Hs.symbols.gmt"
        freeze_piror = true

    # 基因集层配置
    [nnea.geneset_layer]
        min_set_size = 10
        max_set_size = 50
        num_genesets = 30
        attention_dim = 32
        dropout = 0.3
        geneset_threshold = 1e-5
        init_max_epochs = 20 # 2000  # 最大初始化轮数
        init_patience = 40  # 初始化早停耐心值
        # 初始化阶段损失权重配置
        init_task_loss_weight = 1.0  # 任务损失权重（分类损失）
        init_reg_loss_weight = 10.0  # 正则化损失权重（更高的权重）
        init_total_loss_weight = 1.0  # 总损失权重

    [nnea.focus_layer]
        classifier_name = "linear"  # 可选: "linear", "attention"
        hidden_dims = [] # [512, 256] # [256, 128]  # 可以覆盖model.hidden_dims
        classifier_dropout = [0.3, 0.2] # [0.3, 0.2]  # 每个隐藏层的dropout率
        output_dim = 1  # 动态设置输出维度

    [nena.assist_layer]
        use_in_init = true
        dropout = 0.1

# 训练配置
[training]
    epochs = 200
    tailor = false
    tailor_epoch = 100
    tailor_geneset = 1
    batch_size = 32
    learning_rate = 0.0005
    weight_decay = 1e-5
    patience = 10
    regularization_weight = 1

[explain]
    explain_knowledge = "./data/genesets/h.all.v2025.1.Hs.symbols.gmt"