[gobal]
    seed = 888888888
    device = "cuda"
    dataset = 'pbmc3k'
    task = "sc_annotation" # cell_drug, tumor_sur, cell_class, tumor_drug, sc_dimRe, sc_classification, sc_umap, sc_annotation
    model = "nnea"

[piror_knowldege]
    use_piror_knowldege = false
    piror_path = "data/genesets/c1.all.v2025.1.Hs.symbols.gmt"
    freeze_prior = false

[geneset_layer]
    geneset_layer_mode = "one_mode" # one_mode; deep_mod
    use_piror_knowldege = false
    geneset_layer_alpha = 0.25
    num_sets = 20
    set_min_size = 10
    set_max_size = 50
    num_fc_layers = 0

[deep_mod]
    geneset_layers = 2
    sub_num_genesets = 10

[classifier]
    classifier_name = 'linear' # linear or attention
    hidden_dims = [128, 64, 32]
    output_dim = 9 # according to task
    class_names = [0, 1, 2, 3, 4, 5, 6, 7, 8]
    classifier_dropout = [0.4, 0.3]
    pca_dim = 30
    n_neighbors = 30
    min_dist = 0.3

[optimizer]
    lr = 0.001
    opt = "adam"
    opt_scheduler = "reduce"
    opt_factor = 0.5
    opt_patience = 5
    weight_decay = 1e-5

[trainer]
    batch_size = 64
    num_epochs = 10000
    patience_metric = 1
    patience_loss = 5



